apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  labels:
    app: nginx-distroless
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: kyos0109/nginx-distroless:latest
      ports:
        - containerPort: 80
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL