apiVersion: v1
kind: Config

clusters:
- name: kubernetes
  cluster:
    certificate-authority-data: <CA_DATA>
    server: <API_SERVER>

users:
- name: cd
  user:
    token: <TOKEN>

contexts:
- name: cd-context
  context:
    cluster: kubernetes
    user: cd
    namespace: homework

current-context: cd-context