apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: homework

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  selector:
    matchLabels:
      app: web-server

  template:
    metadata:
      labels:
        app: web-server

    spec:
      nodeSelector:
        homework: "true"

      volumes:
        - name: shared-storage
          emptyDir: {}

      initContainers:
        - name: init-content
          image: busybox:1.36
          command: ['sh', '-c', 'echo "<h1>Privet from Init Container!</h1>" > /init/index.html']
          volumeMounts:
            - name: shared-storage
              mountPath: /init

      containers:
        - name: web-server
          image: python:3.9-alpine
          command: ['python', '-m', 'http.server', '8000', '--directory', '/homework']

          ports:
            - containerPort: 8000

          volumeMounts:
            - name: shared-storage
              mountPath: /homework

          readinessProbe:
            exec:
              command:
                - cat
                - /homework/index.html
            initialDelaySeconds: 5
            periodSeconds: 10

          lifecycle:
            preStop:
              exec:
                command: ["rm", "-f", "/homework/index.html"]

