apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
  labels:
    app: web-server
spec:
  volumes:
    - name: shared-storage
      emptyDir: {}

  initContainers:
    - name: init-content
      image: busybox:1.36
      command: ['sh', '-c', 'echo "<h1>Privet from Init Container!</h1>" > /init/index.html']
      volumeMounts:
        - name: shared-storage
          mountPath: /init

  containers:
    - name: web-server
      image: python:3.9-alpine
      command: ['python', '-m', 'http.server', '8000', '--directory', '/homework']
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-storage
          mountPath: /homework
      lifecycle:
        preStop:
          exec:
            command: ["rm", "-f", "/homework/index.html"]
